#!/usr/bin/env node
/**
 * Postbuild step for @conduit/nmh.
 *
 * Chrome's native messaging manifest's `path` field must be an executable.
 * `dist/index.js` is plain JS, so we generate a bash wrapper that invokes
 * it via `node` and chmod it 0755. The Chrome NMH manifest then points at
 * the wrapper, not at the .js file.
 */

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.resolve(here, "..");
const distDir = path.join(pkgRoot, "dist");
const wrapperPath = path.join(distDir, "conduit-nmh.sh");
const indexPath = path.join(distDir, "index.js");

async function main() {
  // Sanity: dist/index.js must exist (built by tsc just before this script).
  try {
    await fs.access(indexPath);
  } catch {
    console.error(
      `[postbuild] expected ${indexPath} to exist; did tsc run?`,
    );
    process.exit(1);
  }

  const wrapper =
    "#!/usr/bin/env bash\n" +
    "# Auto-generated by @conduit/nmh postbuild. Do not edit by hand.\n" +
    'exec /usr/bin/env node "$(dirname "$0")/index.js" "$@"\n';

  await fs.writeFile(wrapperPath, wrapper, { encoding: "utf8" });
  await fs.chmod(wrapperPath, 0o755);

  // Make dist/index.js executable too (it carries a shebang).
  try {
    await fs.chmod(indexPath, 0o755);
  } catch {
    /* non-fatal */
  }

  console.log(`[postbuild] wrote ${wrapperPath} (mode 0755)`);
}

main().catch((err) => {
  console.error("[postbuild] failed:", err);
  process.exit(1);
});
