#!/usr/bin/env node
/**
 * Postbuild step for @conduit/nmh.
 *
 * Chrome's native messaging manifest's `path` field must be an executable.
 * `dist/index.js` is plain JS, so we generate a bash wrapper that invokes
 * it via `node` and chmod it 0755. The Chrome NMH manifest then points at
 * the wrapper, not at the .js file.
 */

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.resolve(here, "..");
const distDir = path.join(pkgRoot, "dist");
const wrapperPath = path.join(distDir, "conduit-nmh.sh");
const indexPath = path.join(distDir, "index.js");

async function main() {
  // Sanity: dist/index.js must exist (built by tsc just before this script).
  try {
    await fs.access(indexPath);
  } catch {
    console.error(
      `[postbuild] expected ${indexPath} to exist; did tsc run?`,
    );
    process.exit(1);
  }

  // Chrome launches NMH processes with a minimal PATH that omits Homebrew
  // (`/opt/homebrew/bin`) and other common node install dirs. Prepend them
  // so `env node` can resolve a node binary; otherwise the wrapper exits 127
  // and the extension reports "Native host has exited" in a reconnect loop.
  //
  // stderr is redirected to ~/.conduit/nmh.log because Chrome discards NMH
  // stderr unless launched with --enable-logging --v=1; without this, NMH
  // crashes leave no trace on disk.
  const wrapper =
    "#!/usr/bin/env bash\n" +
    "# Auto-generated by @conduit/nmh postbuild. Do not edit by hand.\n" +
    'export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"\n' +
    'mkdir -p "$HOME/.conduit"\n' +
    'echo "[wrapper $(date -u +%FT%TZ) pid=$$ ppid=$PPID] invoked, PATH=$PATH" >> "$HOME/.conduit/nmh.log"\n' +
    'exec /usr/bin/env node "$(dirname "$0")/index.js" "$@" 2>>"$HOME/.conduit/nmh.log"\n';

  await fs.writeFile(wrapperPath, wrapper, { encoding: "utf8" });
  await fs.chmod(wrapperPath, 0o755);

  // Make dist/index.js executable too (it carries a shebang).
  try {
    await fs.chmod(indexPath, 0o755);
  } catch {
    /* non-fatal */
  }

  console.log(`[postbuild] wrote ${wrapperPath} (mode 0755)`);
}

main().catch((err) => {
  console.error("[postbuild] failed:", err);
  process.exit(1);
});
