#!/usr/bin/env node
/**
 * Postbuild step for @conduit/nmh.
 *
 * Chrome's native messaging manifest's `path` field must be an executable.
 * `dist/index.js` is plain JS, so we generate a bash wrapper that invokes
 * it via `node` and chmod it 0755. The Chrome NMH manifest then points at
 * the wrapper, not at the .js file.
 *
 * We also produce a single-file ESM bundle at `dist/index.bundle.js` via
 * esbuild. The bundle is what `install-manifest` copies into `~/.conduit/bin/`,
 * which lives outside `~/Documents/` so macOS TCC doesn't block the calling
 * browser from executing it. Bundling lets us avoid copying node_modules.
 */

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build as esbuild } from "esbuild";

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.resolve(here, "..");
const distDir = path.join(pkgRoot, "dist");
const wrapperPath = path.join(distDir, "conduit-nmh.sh");
const indexPath = path.join(distDir, "index.js");
const bundlePath = path.join(distDir, "index.bundle.js");

async function main() {
  // Sanity: dist/index.js must exist (built by tsc just before this script).
  try {
    await fs.access(indexPath);
  } catch {
    console.error(
      `[postbuild] expected ${indexPath} to exist; did tsc run?`,
    );
    process.exit(1);
  }

  // Bundle the NMH so it can be deployed standalone (outside the workspace,
  // outside ~/Documents/) without dragging node_modules along.
  await esbuild({
    entryPoints: [indexPath],
    bundle: true,
    format: "esm",
    platform: "node",
    target: "node20",
    outfile: bundlePath,
    // Keep node built-ins external; they're available at runtime.
    external: ["node:*"],
    logLevel: "warning",
  });
  await fs.chmod(bundlePath, 0o755);

  // Wrapper notes:
  //  - Chrome/Arc launch NMH processes with a bare PATH that omits Homebrew
  //    (`/opt/homebrew/bin`); without prepending it, `env node` exits 127
  //    and the extension reports "Native host has exited" in a reconnect loop.
  //  - stderr is captured to ~/.conduit/nmh.log because Chrome discards NMH
  //    stderr by default; without this, crashes leave no trace on disk.
  //  - Resolves the JS entry relative to its own directory ($(dirname "$0")),
  //    so it works whether run from the build dir or from ~/.conduit/bin/.
  //  - When deployed to ~/.conduit/bin/ the entry filename is
  //    "conduit-nmh.bundle.js"; in dev (running from dist/) we still have
  //    the unbundled "index.js". Try the bundle first, fall back to index.js.
  const wrapper =
    "#!/usr/bin/env bash\n" +
    "# Auto-generated by @conduit/nmh postbuild. Do not edit by hand.\n" +
    'export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"\n' +
    'mkdir -p "$HOME/.conduit"\n' +
    'DIR="$(cd "$(dirname "$0")" && pwd)"\n' +
    'if [ -f "$DIR/conduit-nmh.bundle.js" ]; then ENTRY="$DIR/conduit-nmh.bundle.js"; ' +
    'else ENTRY="$DIR/index.js"; fi\n' +
    'exec /usr/bin/env node "$ENTRY" "$@" 2>>"$HOME/.conduit/nmh.log"\n';

  await fs.writeFile(wrapperPath, wrapper, { encoding: "utf8" });
  await fs.chmod(wrapperPath, 0o755);

  // Make dist/index.js executable too (it carries a shebang).
  try {
    await fs.chmod(indexPath, 0o755);
  } catch {
    /* non-fatal */
  }

  console.log(`[postbuild] wrote ${wrapperPath} (mode 0755)`);
}

main().catch((err) => {
  console.error("[postbuild] failed:", err);
  process.exit(1);
});
